<?php
// $Id$

/**
 * @file
 * UI Slideflow: Integrate the UI.Slideflow slideshow library.
 */


/**
 * Implements hook_theme().
 */
function ss_ui_slides_slideflow_theme($existing, $type, $theme, $path) {
  return array(
    'ss_ui_slides_slideflow' => array(
      'arguments' => array('view' => NULL, 'options' => array(), 'rows' => array(), 'title' => ''),
      'file' => 'ss_ui_slides_slideflow.theme.inc',
    ),
    'views_slideshow_ui_slideflow_controls' =>array(
      'arguments' => array('vss_id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'ss_ui_slides_slideflow.theme.inc',
    ),
    'views_slideshow_ui_slideflow_previous' =>array(
      'arguments' => array('vss_id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'ss_ui_slides_slideflow.theme.inc',
    ),
    'views_slideshow_ui_slideflow_next' =>array(
      'arguments' => array('vss_id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'ss_ui_slides_slideflow.theme.inc',
    ),
  );

}
